# Generated by Django 4.1.5 on 2023-01-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Qntd.'),
        ),
    ]
