# Generated by Django 4.1.5 on 2023-02-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.IntegerField(db_index=True, verbose_name='produto_id'),
        ),
    ]
