# Generated by Django 4.1.5 on 2023-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_itemcarrinho_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
